# Generated by Django 2.2.6 on 2019-10-26 22:15

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default='EUR', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterIndexTogether(
            name='transaction',
            index_together={('from_wallet', 'to_wallet')},
        ),
    ]
